### PR TITLE
added name Thomas in authors screen

### PR DESCRIPTION
**Pull request by senko-tail**

### CODE REVIEW

**Comment by sanlil** [comment]
Looks great! But I think it would be even better for your learning if you tried out some new, unique styling! For example, there's no need to put the name on a row like I did, it could be floating around in the lower right corner, the text upside down or add a color transition. Just play around with it some more and see what you come up with!

**Comment by sanlil** [comment]
Also, I didn't put that in the instructions, but I've realized that we should probably add a screenshot of any visual changes for more efficient reviews.

**Comment by senko-tail** [comment]
added nicer border
Skärmklipp

**Review by SamuelHarner — APPROVED** [review]
Styling looks good!

Custom fonts seem to be platform-specific however, so they don't work on both platforms unless you load them in somehow.

The font Helvetica will for example give this error if you run it on Android:
Screenshot_20201226-124829_Expo

Screenshot_20201226-124843_Expo

See here for more info about fonts: https://www.quora.com/What-fonts-can-I-use-with-React-Native-applications

**Pull request merged**
