### PR TITLE
Update package-lock again

### PR DESCRIPTION
**Pull request by jscarlsson**
I get some more changes in my package-lock

### CODE REVIEW

**Comment by david8611** [comment]
Strange, for some reason whenever I run ```npm install``` on master no changes are made to the package-lock file. However if I run it on this branch the package-lock file is slightly changed again. I'm running node-version: v14.16.1, npm-version: 7.10.0, and expo-version: 4.4.1, which I hope are the latest versions (updated ~3 days ago).

Does anyone else needing this update?

**Comment by SamuelHarner** [comment]
I currently don't get any changes when I run `npm install` on the master branch. I have however already run `npm install` to get the additions from the recent PRs, like #64.

**Comment by jscarlsson** [comment]
I got the exact same changes when I ran `npm install` on a fresh clone just now. I mean it doesn't really matter I guess.

**Comment by jscarlsson** [comment]
These changes were merged with #68, closing.

**Pull request closed without merging**
