### PR TITLE
Add Samuel to Authors screen

### PR DESCRIPTION
**Pull request by SamuelHarner**

### CODE REVIEW

**Comment by sanlil** [comment]
Great that you played around with the colors and the font! If you want to, it would be fun to see some even more unique styling! Remember that it doesn't have to be pretty and unified (we will remove this view later anyway) so make sure to try out something new. For some inspiration: Maybe try to make the box around your name not fill out a whole line. Maybe add rounded corners. Maybe add some spacing between the rows.

I also realized that for future PRs, we should probably add a screenshot when we do a visual change, to make it easier to review.

**Review by sanlil — APPROVED** [review]

**Comment by jscarlsson** [comment]
I can't see the new font on my Android (haven't been able to get it running it in an emulator yet). Might just be a local issue. I can see it on the web version.

**Comment by SamuelHarner** [comment]
> I can't see the new font on my Android (haven't been able to get it running it in an emulator yet). Might just be a local issue. I can see it on the web version.
> 
> I'll quote the exact message I get in case it's interesting: (imo you don't actually need to do anything with this)
> 
> Error
> fontFamily "Futura" is not a system font and has not been loaded through Font-loadAsync.
> 
>     * If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
> 
>     * If this is a custom font, be sure to load it with Font.loadAsync.
>       (And then a bunch technical stuff that I guess might be interesting but I don't want to type it out)
> 
> 
> Again, it's probably just that my phone doesn't support it for some reason, which seems strange and is maybe something to keep in mind I guess, but not a big problem.

Okay thanks, good to know!

I got the same error for certain fonts that I tried out in the iOS simulator, could probably be a platform compatibility issue so might just change to a more standard font to be safe.

**Comment by SamuelHarner** [comment]
Played around a bit more with the styling and changed font back to system standard. Ready to merge the changes.

Latest changes look like this:

Screenshot 2020-12-23 at 11 41 58

**Comment by sanlil** [comment]
Great work! 🌟

**Review by jscarlsson — APPROVED** [review]
Yeah, that looks good, and no errors for me.

**Pull request merged**
