### PR TITLE
Fixed header styling to look like prototype

### PR DESCRIPTION
**Pull request by epulls**
Bara små förändringar i style sheets

### CODE REVIEW

**Comment by adavado** [comment]
IMG_5979
IMG_5980

**Comment by adavado** [comment]
Android (still bugging with FAB)
Screenshot_20210222-161324_Expo_Go
Screenshot_20210222-161358_Expo_Go

**Comment by adavado** [comment]
iOS
IMG_5982
IMG_5981

**Review by adavado — APPROVED** [review]
Works as expected, other bugs updated in Trello!

**Comment by david8611** [comment]
> Android (still bugging with FAB)
> Screenshot_20210222-161324_Expo_Go
> Screenshot_20210222-161358_Expo_Go

Are you using an android emulator when testing the alignment of the FAB-button. I found this to be very strange, I have no issues on my personal android phone. If this problem persist i believe the only solution is to decide a fixed size of the navbar..

**Comment by david8611** [comment]
Also, isn't there any option to apply these style changes more globally in order to add for example the rounded corners to every screen?

**Comment by david8611** [comment]
The FAB button issue should be fixed here: https://github.com/ovulai/ovulai-react-native-app/pull/38/commits/a898e374219016f28a7a0138055f2882da6686de, it is merged to master

**Pull request merged**
