### PR TITLE
Getting history view to use stored data

### PR DESCRIPTION
**Pull request by editf**
I think the view was supposed to be endlessly scrollable but I'm not really sure how to make that happen so I figured I would start by loading 30 days of data.

I can't get this to work properly and I'm not really sure what the problem is. One problem seems to be that the date I'm trying to send to the `getMonth` function becomes undefined after calling the function. When trying to use `getData` for a certain date (today) and printing it to the terminal I get 
```
Object {
    "_U": 0,
    "_V": 0,
    "_W": null,
    "_X": null,
  }
```
which I guess might be having the same issue with the date not being passed properly but I'm not sure if there might be another issue there as well.

### CODE REVIEW

**Comment by david8611** [comment]
From what I've experienced when using async functions is that it is not suitable to return any data from the async function. It is generally better to define a state variable using the hook ```useState``` which you can send in as a parameter together with its mutable function. You can then mutate the state variable using its own state function insider the async function when gathering the data. 

The async function returns a promise object which I haven't been successful in unwrapping, hence the reason why I've chosen to hold certain data in a state variable which Will be mutated each time the async (sideeffect) function in the hook useEffect executes which is dependent on its second argument in the array.

 Nice start overall, I Will help you with this if I have some time left. Otherwise try to have a look at the lane-tracking component in LaneInput.jsx and basically use the same method as done there.

**Comment by david8611** [comment]
I have now made several code adjustments to fetch and display the stored data in the history view. I currently have some difficulties with displaying the icons. Maybe it has something to do with the keys applied to the component, I don't know. I will most likely not be able to continue working (based on the limited time available) on this and therefore I would appreciate if someone else can take a look and make some adjustments if needed.

Tip: The user should be able to scroll up to the top to render more history, try it!

**Review by david8611 — APPROVED** [review]
Initial fetching of data should be done, however the rendering of the icons needs to be fixed either in this PR or in another one.

**Comment by sanlil** [comment]
Screenshot 2021-05-01 at 16 21 28

**Pull request merged**
