### PR TITLE
Update package lock file

### PR DESCRIPTION
**Pull request by sanlil**
Not sure why I have 25k lines addition to the package-lock file when I do `npm install` 🤔 Anyone else having the same or is it just me? Have we forgotten to commit the changes to the package-lock or do I have a different version of something compared to the rest of you?

### CODE REVIEW

**Comment by david8611** [comment]
Strange, I don't seem to have the same behavior of the package-lock file. I've both updated the expo client to the latest version and run ```npm install``` without any updates to the package-lock file.

**Comment by jscarlsson** [comment]
I get this too but I didn't know what to do with it. I've just stashed it every time it happened.

**Review by jscarlsson — APPROVED** [review]
I believe it's just that the structure of the file is changed somehow. I think the stuff that's added is already there but in a different form. Not sure how relevant it is to try to do something about it or if we should just merge this.

**Comment by sanlil** [comment]
Let's try merging it and see if others (like David) now get huge diffs instead

**Pull request merged**
