### PR TITLE
Tracking view modification from tracking settings

### PR DESCRIPTION
**Pull request by david8611**
This is basically only a draft of the tracking view result screen, adding Thomas tabs, etc. I currently have some issues selecting different colors for each label-text in the tabs which would be great if someone could take a look at it. I've also added an implementation of only displaying the desired tracking options in the view based on the tracking settings. From what I've understood the tracking view is different from the actual tracking screen where user inputs are available, and the tracking view will display the results? Also how are we navigating between the tracking view to the date selected tracking screen with the user inputs available? My suggestion is to start implementing the actual input and result screen first and then save each input to the local storage (AsyncStorage) and only show options selected from TrackingSettings (also stored in the local Storage). (Edit: All these questions have been answered on slack)

The ability to be able to navigate to the tracking screen using the fab (+) button still needs to implemented, maybe using the onPress prop on the homescreen where the fab is located? EDIT: Aaron added the navigation from the plus button in https://github.com/ovulai/ovulai-react-native-app/pull/52/commits/9e2ea6e386a1cab0cccf4d22759f702a6fbd94d3

### CODE REVIEW

**Comment by david8611** [comment]
It seems that the current solution to apply different colors to each tab label is to create your own TabBar, inserting the MaterialTopTabNavigator with a prop applying one color to each tab as seen from the response here: https://stackoverflow.com/questions/47406755/how-to-set-different-colors-for-each-tab-in-react-native

**Comment by david8611** [comment]
I'm soon going to update this branch, remove the tabs allowing for the input lanes to be created based on the tracking settings.

**Comment by sanlil** [comment]
Nice work with the tabs! They look great (and the different text color on the tabs is not that important)!

Please put this PR aside and save for later (so we don't have to reimplement the tabs later on) but as you suggested, start with making sure that we have the date navigation, tracking lanes and saving to local storage in place first since that's more important to get in place.

**Comment by david8611** [comment]
Left as archive possibly for later. See #54 for an updated version.

**Pull request closed without merging**
