### PR TITLE
Remove Tracking from Drawer

### PR DESCRIPTION
**Pull request by SamuelHarner**

### CODE REVIEW

**Comment by SamuelHarner** [comment]
Since navigation to Tracking used to be handled by the DrawerNavigation component, removing Tracking from the Drawer requires navigation to Tracking to be handled by another Navigation component.

To solve this I have added a StackNavigator and nested both the DrawerNavigation and TrackingNavigation in the Stack. This solution seems to work, with the exception that it causes problems for the `useIsDrawerOpen()` hook in `Tracking.jsx`. I have therefore temporarily commented out the code with that hook in commit 199ef95 as solutions for this issue are looked into.

**Comment by sanlil** [comment]
@SamuelHarner It sounds like you need to rebase your branch on master because `useIsDrawerOpen` is not used in the Tracking view anymore

**Comment by SamuelHarner** [comment]
@sanlil Cool, thanks for the heads up!

**Review by david8611 — APPROVED** [review]
Everything seems to work correctly on Android 👍 , with some smoother animations added when navigation.

**Pull request merged**
