### PR TITLE
date navigation for tracking view

### PR DESCRIPTION
**Pull request by adavado**

### CODE REVIEW

**Comment by adavado** [comment]
File_000

**Comment by david8611** [comment]
Nice implementation, works well from what I can see. It might be worth discussing whether we should convert this dateBar to a functional component and maybe render/display it inside the tracking screen itself for easier access when storing or fetching local input data?

**Review by SamuelHarner — COMMENTED** [review]
@adavado Nice work! Component looks good and works as desired, just needs some finishing touches!

I have some ideas on how we can use libraries to format the date as we want it, and add support for internationalization. I think this could be a good library to use: https://date-fns.org/

Also, as @david8611 suggests, we can look into converting it into a functional component.

**Comment by adavado** [comment]
Will continue working on converting to functional component, keep getting different _component exceptions_ for the most basic stuff..

**Comment by adavado** [comment]
Further development in another task is support for internalization, which works standalone in date-fns with `import { sv } from 'date-fns/locale'`, although I couldn't find a solution to pass through locale from i18n. Also, we use `se` in i18n as opposed to `sv`. I suggest we change in i18n to what I understand to be the international standard for swedish which would simplify keeping the language consistent for the date formatting. Assuming it's possible to pass localize properties with date-fns, since it was possible without it.

**Comment by SamuelHarner** [comment]
Nice work on the changes and addition of navigation, @adavado !

I have moved the `useState` of the date state from the DateBar component to the Tracking screen, so that the selected date will be easily accessible to other components on the Tracking screen, for example input components that may want to store the date of input along with the user input.

I think that may be the final adjustment needed for now, so unless there are any other issues that come to mind we might be ready to merge this PR!

**Review by SamuelHarner — APPROVED** [review]

**Comment by SamuelHarner** [comment]
iOS simulator screenshot of current Tracking screen

**Pull request merged**
